#!/bin/bash

# Clear the screen
clear

# Define the save location
save_location="../Desktop"

# Prompt the user for the recipe name
read -p "Yemeğin adı nedir? " recipe_name

# Replace spaces with hyphens in the recipe name
recipe_title="${recipe_name// /-}"

# Define an array of categories
categories=("çorba" "tatlı" "düz yemek")

# Clear the screen
clear

# Prompt the user to select a category
echo "$recipe_name için bi kategori seç"
select category in "${categories[@]}"; do
  if [[ " ${categories[@]} " =~ " $category " ]]; then
    # Category is valid
    break
  else
    echo "olmadı bida dene."
  fi
done

# Clear the screen
clear

# Prompt the user for the number of servings
read -p "kaç kişilik bir tarif bu: " servings

# Prompt the user for the preparation time in minutes
read -p "Bu tarifi hazırlamak kaç dakika sürer? " prep_time


# Initialize an empty ingredients list
ingredients=""

# Clear the screen
clear

# Prompt the user for ingredients until they choose to stop (by pressing Enter)
echo "$recipe_name için gerekli malzemeler nelerdir? (Her malzeme için yeni satır açın ve boş satır girerek bitirin)"
while read -r ingredient; do
  if [ -z "$ingredient" ]; then
    break
  fi
  # Add each ingredient as a new line
  ingredients+="    * $ingredient"$'\n'
done

# Clear the screen
clear

# Initialize an empty directions list
directions=""

# Initialize a direction counter
direction_count=1

# Prompt the user for directions until they choose to stop (by pressing Enter)
echo "$recipe_name yaparkenki adımlar nelerdir? (Her adım için yeni satır açın ve boş satır girerek bitirin)"
while read -r direction; do
  if [ -z "$direction" ]; then
    break
  fi
  # Add each direction as a new line
  directions+="    $direction_count. $direction"$'\n'
  ((direction_count++))
done

# Define the file name for the generated Markdown file
output_file="$save_location$(date +'%Y-%m-%d')-$recipe_title.md"

# Define the content of the Markdown file
markdown_content="---
date: $(date +'%Y-%m-%d')
title: $recipe_name
permalink: $recipe_title
categories:
  - $category

recipe:
  servings: $servings kişilik
  prep: $prep_time dk falan
  ingredients_markdown: |-
$ingredients
  directions_markdown: |-
$directions
---"

# Write the content to the output file
echo "$markdown_content" > "$output_file"
echo -n "$markdown_content" | pbcopy
echo copy done


echo "Recipe Generated As: $output_file"
